parameters:
  # apache_dir: '~/.amp/apache.d'
  # nginx_dir: '~/.amp/nginx.d'
  mysql_type: 'dsn'
  mysql_dsn: ''
  #'mysql://root:root@127.0.0.1:3307'
  #''

services:
  ## Data storage for AMP instances
  instances:
    class: Amp\InstanceRepository
    calls:
      - [setFile, ['%instances_yml%']]
      - [setDb, ['@mysql']]
      - [setHttpd, ['@httpd.apache']]

  ## This database connection used for most environments
  mysql.cli:
    class: Amp\Database\MySQLCLI

  mysql.dsn:
    class: Amp\Database\MySQL
    calls:
      - [setAdminDsn, ['%mysql_dsn%']]

  ## This database connection used for ephemeral, performance-oriented test environments
  mysql.linuxRamDisk:
    class: Amp\Database\MySQLinuxRAMServer
    properties:
      pid: '%project%/app/tmp/mysqld.pid'
      ramdisk: '%project%/app/tmp/mysqld'
      name: '%prefix%_%env%'

  httpd.apache:
    class: Amp\Httpd\VhostTemplate
    calls:
      - [setTemplateEngine, ['@template.engine']]
      - [setTemplate, ['apache-vhost.php']]
      - [setDir, ['%apache_dir%']]

  httpd.nginx:
    class: Amp\Httpd\VhostTemplate
    calls:
      - [setTemplateEngine, ['@template.engine']]
      - [setTemplate, ['nginx-vhost.php']]
      - [setDir, ['%nginx_dir%']]

  template.engine:
    class: Symfony\Component\Templating\PhpEngine
    factory_class: Amp\TemplateEngineFactory
    factory_method: get