parameters:
  # amp_src_dir: (varies; local-dir or phar)
  # app_dir: '~/.amp'
  # instances_yml: '~/.amp/instances.yml'
  # config_yml: '%app_dir%/services.yml'

  httpd_type: 'apache'

  # apache_dir: '~/.amp/apache.d'
  apache_tpl: 'apache-vhost.php'

  # nginx_dir: '~/.amp/nginx.d'
  nginx_tpl: 'nginx-vhost.php'

  mysql_type: 'dsn'
  mysql_dsn: ''

services:
  ## Data storage for AMP instances
  instances:
    class: Amp\InstanceRepository
    calls:
      - [setFileMode, [0600]]
      - [setFile, ['%instances_yml%']]
      - [setDb, ['@mysql']]
      - [setHttpd, ['@httpd']]

  ## This database connection used for most environments
  mysql.cli:
    class: Amp\Database\MySQLCLI

  mysql.dsn:
    class: Amp\Database\MySQL
    calls:
      - [setAdminDsn, ['%mysql_dsn%']]

  ## This database connection used for ephemeral, performance-oriented test environments
  mysql.linuxRamDisk:
    class: Amp\Database\MySQLinuxRAMServer
    properties:
      pid: '%project%/app/tmp/mysqld.pid'
      ramdisk: '%project%/app/tmp/mysqld'
      name: '%prefix%_%env%'

  httpd.apache:
    class: Amp\Httpd\VhostTemplate
    calls:
      - [setTemplateEngine, ['@template.engine']]
      - [setTemplate, ['%apache_tpl%']]
      - [setDir, ['%apache_dir%']]

  httpd.nginx:
    class: Amp\Httpd\VhostTemplate
    calls:
      - [setTemplateEngine, ['@template.engine']]
      - [setTemplate, ['%nginx_tpl%']]
      - [setDir, ['%nginx_dir%']]

  config.repository:
    class: Amp\ConfigRepository
    calls:
      - [setFileMode, [0600]]
      - [setFile, ['%config_yml%']]

  template.engine:
    class: Symfony\Component\Templating\PhpEngine
    factory_class: Amp\TemplateEngineFactory
    factory_method: get